console.log("foo");
const Bar = require("./bar.js");
const Qux = require("qux");
exports.Bar = Bar;
exports.Qux = Qux;
exports.global = ""+global;
exports.Buffer = ""+Buffer;
exports.process = ""+process;
exports.__dirname = __dirname;
exports.__filename = __filename;